### ISSUE TITLE
LSLAPPS_AMTIForcePlate was enabled, but its folder is either nonexistent or not checked out

### ISSUE THREAD

**Issue by Isastol** [labstreaminglayer/App-AMTIForcePlate#1]
Hi,

I'm trying to get the AMTI forceplate app running but I get this error message every time I try "LSLAPPS_AMTIForcePlate was enabled, but its folder is either nonexistent or not checked out". Is it necessary to have the AMTI Software to get the plate connected to LSL. I can't find the problem and I can't find an .exe file in the repository, to get it running.

I would be very happy, if someone could help me.

Best regards,
Isabel

**Comment by cboulay** [comment]
The builds still exists on ftp://sccn.ucsd.edu/pub/software/LSL/Apps

Unfortunately, Chrome and other browsers have removed FTP browsing so it's not as easy to download as in the past. Here's the latest build:

[AMTIForcePlate-1.12.zip](https://github.com/labstreaminglayer/App-AMTIForcePlate/files/12524132/AMTIForcePlate-1.12.zip)
